command_timeout = 1000
add_newline = true

format = """
  $directory\
  $git_branch\
  $git_status\
  $fill\
  $python\
  $nodejs\
  $lua\
  $rust\
  $php\
  $java\
  $kotlin\
  $dotnet\
  $package
  $character"""

palette = "catppuccin_mocha"
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[fill]
symbol = ' '

[character]
success_symbol = '[](bold green) '
error_symbol = '[](bold red) '

[directory]
disabled = false
read_only = " "
truncation_length = 4
truncate_to_repo = false
format = "[$read_only](blue)[$path](lavender)"

[git_status]
stashed = "  \\(${count}\\) "
ahead = "  \\(${count}\\)"
behind = "  \\(${count}\\)"
diverged = "  ${ahead_count} ${behind_count}"
conflicted = "  \\(${count}\\)"
deleted = "  \\(${count}\\)"
renamed = " 󰑕 \\(${count}\\)"
modified = "  \\(${count}\\)"
staged = "  \\(${count}\\)"
untracked = "  \\(${count}\\)"
format = "( [](peach)[$all_status$ahead_behind](bg:peach fg:surface0)[](peach)) "

[git_branch]
symbol = " "
format = " [](peach)[$symbol$branch](bg:peach fg:surface0)[](peach)"

[package]
display_private = true
version_format = "v${raw}"
format = " [ ](yellow)[$version](text)"

#=== languages ===

[nodejs]
format = " [](bold green)[ ($version )](bg:green fg:surface0)[](bold green)"

[python]
pyenv_prefix = 'venv '
python_binary = ["python", "python2", "python3"]
format = '([ \($virtualenv\)](peach)) [](bold blue)[ ${pyenv_prefix}(${version})](bg:blue fg:surface0)[](bold blue)'

[lua]
format = ' [](bold blue)[  ($version )](bg:blue fg:surface0)[](bold blue)'

[rust]
format = ' [](bold red)[ ($version )](bg:red fg:surface0)[](bold red)'

[java]
format = ' [](bold red)[ ($version )](bg:red fg:surface0)[](bold red)'

[kotlin]
detect_files = [
  'pom.xml',
  'build.gradle.kts',
  'build.sbt',
  '.java-version',
  'deps.edn',
  'project.clj',
  'build.boot',
  '.sdkmanrc',
]
format = ' [](bold mauve)[ ($version )](bg:mauve fg:surface0)[](bold mauve)'

[dotnet]
detect_extensions = ['csproj', 'fsproj', 'xproj', 'cs']
format = ' [](bold mauve)[󰪮 ($version )](bg:mauve fg:surface0)[](bold mauve)'

[php]
format = ' [](bold mauve)[ ($version )](bg:mauve fg:surface0)[](bold mauve)'

[bun]
symbol = ""
