return {
  -- "nvim-treesitter/nvim-treesitter",
  -- branch = "main",
  -- event = { "User FileOpened", "VeryLazy" },
  -- version = false,
  -- cmd = { "TSInstall", "TSUpdate", "TSLog", "TSUninstall" },
  -- opts_extend = { "ensure_installed" },
  -- opts = {
  --   indent = { enable = true },
  --   highlight = { enable = true },
  --   folds = { enable = true },
  --   ensure_installed = {
  --     "python",
  --     "prisma",
  --     "html",
  --     "css",
  --     "javascript",
  --     "json",
  --     "lua",
  --     "toml",
  --     "luadoc",
  --     "typescript",
  --     "tsx",
  --     "astro",
  --     "yaml",
  --     "http",
  --     "markdown",
  --     "markdown_inline",
  --     "latex",
  --     "xml",
  --     "graphql",
  --     "regex",
  --   },
  -- },
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "master",
    lazy = false,
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup {
        ensure_installed = {
          "python",
          "html",
          "css",
          "javascript",
          "json",
          "lua",
          "toml",
          "luadoc",
          "typescript",
          "tsx",
          "astro",
          "yaml",
          "http",
          "markdown",
          "markdown_inline",
          "latex",
          "xml",
          "graphql",
          "regex",
          "prisma",
        },

        sync_install = false,

        auto_install = true,

        highlight = { enable = true },
      }
    end,
  },
}
